# Generated by Django 5.2.3 on 2025-06-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termek', models.CharField(blank=True, max_length=100, null=True)),
                ('mennyiseg', models.IntegerField(blank=True, null=True)),
                ('meret', models.CharField(blank=True, max_length=50, null=True)),
                ('atvetel_datuma', models.DateField(blank=True, null=True)),
                ('atvetel_idoppontja', models.TimeField(blank=True, null=True)),
                ('nev', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonszam', models.CharField(blank=True, max_length=50, null=True)),
                ('tipus', models.CharField(blank=True, choices=[('elvitel', 'Elvitel'), ('helyben fogyasztas', 'Helyben fogyasztás')], max_length=20, null=True)),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('letrehozva', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
